// <auto-generated />
using System;
using KitchenFlow.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KitchenFlow.Api.Migrations
{
    [DbContext(typeof(KitchenFlowDbContext))]
    [Migration("20260915081723_AddCookingTask")]
    partial class AddCookingTask
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("KitchenFlow.Api.Models.CookingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrecedenceTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RequiredIngredientAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequiredIngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredMachineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrecedenceTaskId");

                    b.HasIndex("RequiredMachineId");

                    b.ToTable("CookingTasks");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityMl")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxTempC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinTempC")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacityMl = 0,
                            IsAvailable = true,
                            Kind = "",
                            MaxTempC = 0,
                            MinTempC = 0,
                            Name = "오븐"
                        },
                        new
                        {
                            Id = 2,
                            CapacityMl = 0,
                            IsAvailable = true,
                            Kind = "",
                            MaxTempC = 0,
                            MinTempC = 0,
                            Name = "믹서"
                        },
                        new
                        {
                            Id = 3,
                            CapacityMl = 0,
                            IsAvailable = true,
                            Kind = "",
                            MaxTempC = 0,
                            MinTempC = 0,
                            Name = "냉장고"
                        });
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.CookingTask", b =>
                {
                    b.HasOne("KitchenFlow.Api.Models.CookingTask", null)
                        .WithMany()
                        .HasForeignKey("PrecedenceTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KitchenFlow.Api.Models.Machine", null)
                        .WithMany()
                        .HasForeignKey("RequiredMachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
