// <auto-generated />
using System;
using KitchenFlow.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KitchenFlow.Api.Migrations
{
    [DbContext(typeof(KitchenFlowDbContext))]
    [Migration("20260928065601_AddStepDependencyAndMachineSeed")]
    partial class AddStepDependencyAndMachineSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "물",
                            StockQty = 10000m,
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 2,
                            Name = "라면",
                            StockQty = 20m,
                            Unit = "개"
                        },
                        new
                        {
                            Id = 3,
                            Name = "양파",
                            StockQty = 3000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 4,
                            Name = "당근",
                            StockQty = 2000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 5,
                            Name = "양배추",
                            StockQty = 2000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 6,
                            Name = "식용유",
                            StockQty = 1000m,
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 7,
                            Name = "간장",
                            StockQty = 1000m,
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 8,
                            Name = "닭",
                            StockQty = 5000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 9,
                            Name = "버터",
                            StockQty = 500m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 10,
                            Name = "소금",
                            StockQty = 1000m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 11,
                            Name = "후추",
                            StockQty = 200m,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 12,
                            Name = "마늘",
                            StockQty = 500m,
                            Unit = "g"
                        });
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.CookingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrecedenceTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RequiredIngredientAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequiredIngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredMachineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrecedenceTaskId");

                    b.HasIndex("RequiredMachineId");

                    b.ToTable("CookingTasks");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityMl")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxTempC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinTempC")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacityMl = 50000,
                            IsAvailable = true,
                            Kind = "Oven",
                            MaxTempC = 250,
                            MinTempC = 50,
                            Name = "오븐"
                        },
                        new
                        {
                            Id = 2,
                            CapacityMl = 5000,
                            IsAvailable = true,
                            Kind = "Mixer",
                            MaxTempC = 40,
                            MinTempC = 0,
                            Name = "믹서"
                        },
                        new
                        {
                            Id = 3,
                            CapacityMl = 200000,
                            IsAvailable = true,
                            Kind = "Fridge",
                            MaxTempC = 10,
                            MinTempC = -20,
                            Name = "냉장고"
                        },
                        new
                        {
                            Id = 4,
                            CapacityMl = 5000,
                            IsAvailable = true,
                            Kind = "Induction",
                            MaxTempC = 240,
                            MinTempC = 30,
                            Name = "인덕션"
                        },
                        new
                        {
                            Id = 5,
                            CapacityMl = 10000,
                            IsAvailable = true,
                            Kind = "Scale",
                            MaxTempC = 40,
                            MinTempC = 0,
                            Name = "저울"
                        });
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "라면"
                        },
                        new
                        {
                            Id = 2,
                            Name = "야채볶음"
                        },
                        new
                        {
                            Id = 3,
                            Name = "로스트치킨"
                        });
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TempC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("RecipeId", "Order");

                    b.ToTable("Steps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "물 끓이기",
                            DurationMinutes = 5,
                            MachineId = 4,
                            Order = 1,
                            RecipeId = 1,
                            TempC = 100
                        },
                        new
                        {
                            Id = 2,
                            Action = "면·스프 넣기",
                            DurationMinutes = 1,
                            MachineId = 4,
                            Order = 2,
                            RecipeId = 1,
                            TempC = 100
                        },
                        new
                        {
                            Id = 3,
                            Action = "끓이기",
                            DurationMinutes = 4,
                            MachineId = 4,
                            Order = 3,
                            RecipeId = 1,
                            TempC = 100
                        },
                        new
                        {
                            Id = 4,
                            Action = "채소 계량",
                            DurationMinutes = 2,
                            MachineId = 5,
                            Order = 1,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Action = "양념 섞기",
                            DurationMinutes = 2,
                            MachineId = 2,
                            Order = 2,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 6,
                            Action = "팬 예열",
                            DurationMinutes = 3,
                            MachineId = 4,
                            Order = 3,
                            RecipeId = 2,
                            TempC = 180
                        },
                        new
                        {
                            Id = 7,
                            Action = "채소 볶기",
                            DurationMinutes = 5,
                            MachineId = 4,
                            Order = 4,
                            RecipeId = 2,
                            TempC = 200
                        },
                        new
                        {
                            Id = 8,
                            Action = "양념 넣고 볶기",
                            DurationMinutes = 2,
                            MachineId = 4,
                            Order = 5,
                            RecipeId = 2,
                            TempC = 200
                        },
                        new
                        {
                            Id = 9,
                            Action = "남은 재료 보관",
                            DurationMinutes = 1,
                            MachineId = 3,
                            Order = 6,
                            RecipeId = 2,
                            TempC = 4
                        },
                        new
                        {
                            Id = 10,
                            Action = "오븐 예열",
                            DurationMinutes = 10,
                            MachineId = 1,
                            Order = 1,
                            RecipeId = 3,
                            TempC = 200
                        },
                        new
                        {
                            Id = 11,
                            Action = "닭 꺼내기",
                            DurationMinutes = 1,
                            MachineId = 3,
                            Order = 2,
                            RecipeId = 3,
                            TempC = 4
                        },
                        new
                        {
                            Id = 12,
                            Action = "닭 무게 재기",
                            DurationMinutes = 1,
                            MachineId = 5,
                            Order = 3,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 13,
                            Action = "양념 계량",
                            DurationMinutes = 2,
                            MachineId = 5,
                            Order = 4,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 14,
                            Action = "허브버터 만들기",
                            DurationMinutes = 3,
                            MachineId = 2,
                            Order = 5,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 15,
                            Action = "1차 굽기",
                            DurationMinutes = 30,
                            MachineId = 1,
                            Order = 6,
                            RecipeId = 3,
                            TempC = 200
                        },
                        new
                        {
                            Id = 16,
                            Action = "뒤집기",
                            DurationMinutes = 1,
                            MachineId = 1,
                            Order = 7,
                            RecipeId = 3,
                            TempC = 200
                        },
                        new
                        {
                            Id = 17,
                            Action = "2차 굽기",
                            DurationMinutes = 25,
                            MachineId = 1,
                            Order = 8,
                            RecipeId = 3,
                            TempC = 200
                        },
                        new
                        {
                            Id = 18,
                            Action = "버터 소스 끓이기",
                            DurationMinutes = 5,
                            MachineId = 4,
                            Order = 9,
                            RecipeId = 3,
                            TempC = 120
                        },
                        new
                        {
                            Id = 19,
                            Action = "마무리 굽기",
                            DurationMinutes = 10,
                            MachineId = 1,
                            Order = 10,
                            RecipeId = 3,
                            TempC = 230
                        },
                        new
                        {
                            Id = 20,
                            Action = "휴지",
                            DurationMinutes = 10,
                            MachineId = 1,
                            Order = 11,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 21,
                            Action = "완성 무게 확인",
                            DurationMinutes = 1,
                            MachineId = 5,
                            Order = 12,
                            RecipeId = 3
                        });
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.StepDependency", b =>
                {
                    b.Property<int>("StepId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DependsOnStepId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StepId", "DependsOnStepId");

                    b.HasIndex("DependsOnStepId");

                    b.ToTable("StepDependencies");

                    b.HasData(
                        new
                        {
                            StepId = 2,
                            DependsOnStepId = 1
                        },
                        new
                        {
                            StepId = 3,
                            DependsOnStepId = 2
                        },
                        new
                        {
                            StepId = 7,
                            DependsOnStepId = 4
                        },
                        new
                        {
                            StepId = 7,
                            DependsOnStepId = 6
                        },
                        new
                        {
                            StepId = 8,
                            DependsOnStepId = 5
                        },
                        new
                        {
                            StepId = 8,
                            DependsOnStepId = 7
                        },
                        new
                        {
                            StepId = 9,
                            DependsOnStepId = 8
                        },
                        new
                        {
                            StepId = 12,
                            DependsOnStepId = 11
                        },
                        new
                        {
                            StepId = 14,
                            DependsOnStepId = 13
                        },
                        new
                        {
                            StepId = 15,
                            DependsOnStepId = 10
                        },
                        new
                        {
                            StepId = 15,
                            DependsOnStepId = 12
                        },
                        new
                        {
                            StepId = 15,
                            DependsOnStepId = 14
                        },
                        new
                        {
                            StepId = 16,
                            DependsOnStepId = 15
                        },
                        new
                        {
                            StepId = 17,
                            DependsOnStepId = 16
                        },
                        new
                        {
                            StepId = 19,
                            DependsOnStepId = 17
                        },
                        new
                        {
                            StepId = 19,
                            DependsOnStepId = 18
                        },
                        new
                        {
                            StepId = 20,
                            DependsOnStepId = 19
                        },
                        new
                        {
                            StepId = 21,
                            DependsOnStepId = 20
                        });
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.StepInput", b =>
                {
                    b.Property<int>("StepId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.HasKey("StepId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("StepInputs");

                    b.HasData(
                        new
                        {
                            StepId = 1,
                            IngredientId = 1,
                            Quantity = 550m
                        },
                        new
                        {
                            StepId = 2,
                            IngredientId = 2,
                            Quantity = 1m
                        },
                        new
                        {
                            StepId = 4,
                            IngredientId = 3,
                            Quantity = 150m
                        },
                        new
                        {
                            StepId = 4,
                            IngredientId = 4,
                            Quantity = 100m
                        },
                        new
                        {
                            StepId = 4,
                            IngredientId = 5,
                            Quantity = 200m
                        },
                        new
                        {
                            StepId = 5,
                            IngredientId = 7,
                            Quantity = 30m
                        },
                        new
                        {
                            StepId = 6,
                            IngredientId = 6,
                            Quantity = 20m
                        },
                        new
                        {
                            StepId = 11,
                            IngredientId = 8,
                            Quantity = 1200m
                        },
                        new
                        {
                            StepId = 13,
                            IngredientId = 10,
                            Quantity = 10m
                        },
                        new
                        {
                            StepId = 13,
                            IngredientId = 11,
                            Quantity = 3m
                        },
                        new
                        {
                            StepId = 13,
                            IngredientId = 12,
                            Quantity = 20m
                        },
                        new
                        {
                            StepId = 14,
                            IngredientId = 9,
                            Quantity = 50m
                        },
                        new
                        {
                            StepId = 18,
                            IngredientId = 9,
                            Quantity = 30m
                        });
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.CookingTask", b =>
                {
                    b.HasOne("KitchenFlow.Api.Models.CookingTask", null)
                        .WithMany()
                        .HasForeignKey("PrecedenceTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KitchenFlow.Api.Models.Machine", null)
                        .WithMany()
                        .HasForeignKey("RequiredMachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.Step", b =>
                {
                    b.HasOne("KitchenFlow.Api.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KitchenFlow.Api.Models.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.StepDependency", b =>
                {
                    b.HasOne("KitchenFlow.Api.Models.Step", "DependsOn")
                        .WithMany()
                        .HasForeignKey("DependsOnStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KitchenFlow.Api.Models.Step", "Step")
                        .WithMany("DependsOn")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOn");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.StepInput", b =>
                {
                    b.HasOne("Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KitchenFlow.Api.Models.Step", "Step")
                        .WithMany("Inputs")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.Recipe", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.Step", b =>
                {
                    b.Navigation("DependsOn");

                    b.Navigation("Inputs");
                });
#pragma warning restore 612, 618
        }
    }
}
