// <auto-generated />
using System;
using KitchenFlow.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KitchenFlow.Api.Migrations
{
    [DbContext(typeof(KitchenFlowDbContext))]
    [Migration("20260927142822_AddRecipeStepsAndInputs")]
    partial class AddRecipeStepsAndInputs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockQty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.CookingTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrecedenceTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("RequiredIngredientAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequiredIngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredMachineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrecedenceTaskId");

                    b.HasIndex("RequiredMachineId");

                    b.ToTable("CookingTasks");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityMl")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxTempC")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinTempC")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacityMl = 0,
                            IsAvailable = true,
                            Kind = "",
                            MaxTempC = 0,
                            MinTempC = 0,
                            Name = "오븐"
                        },
                        new
                        {
                            Id = 2,
                            CapacityMl = 0,
                            IsAvailable = true,
                            Kind = "",
                            MaxTempC = 0,
                            MinTempC = 0,
                            Name = "믹서"
                        },
                        new
                        {
                            Id = 3,
                            CapacityMl = 0,
                            IsAvailable = true,
                            Kind = "",
                            MaxTempC = 0,
                            MinTempC = 0,
                            Name = "냉장고"
                        });
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TempC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("RecipeId", "Order");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.StepInput", b =>
                {
                    b.Property<int>("StepId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.HasKey("StepId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("StepInputs");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.CookingTask", b =>
                {
                    b.HasOne("KitchenFlow.Api.Models.CookingTask", null)
                        .WithMany()
                        .HasForeignKey("PrecedenceTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KitchenFlow.Api.Models.Machine", null)
                        .WithMany()
                        .HasForeignKey("RequiredMachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.Step", b =>
                {
                    b.HasOne("KitchenFlow.Api.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KitchenFlow.Api.Models.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.StepInput", b =>
                {
                    b.HasOne("Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KitchenFlow.Api.Models.Step", "Step")
                        .WithMany("Inputs")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.Recipe", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("KitchenFlow.Api.Models.Step", b =>
                {
                    b.Navigation("Inputs");
                });
#pragma warning restore 612, 618
        }
    }
}
